# This file contains values from Cookiecutter

default_context:
  project_name: "kle2netlist"
  project_description: "KiCad netlist generator for mechanical keyboards "
  organization: "kle2netlist"
  license: "MIT"
  version: "0.1.0"
  github_name: "adamws"
  email: "adamws@users.noreply.github.com"
