id := `id -u $(whoami)`
output := "output/udb.kicad_pcb"

plot_front_order := "B.Cu,F.Cu,F.Silkscreen,Edge.Cuts"
plot_back_order := "F.Cu,B.Cu,B.Silkscreen,Edge.Cuts"

venv:
  #!/usr/bin/env bash
  rm -rf .env
  python -m venv --system-site-package .env
  . .env/bin/activate
  pip install -r requirements.txt

svg pcb_file order="front":
  #!/usr/bin/env bash
  set -euxo pipefail
  if [ "{{order}}" = "front" ]; then
    layers="{{plot_front_order}}"
    output_file="resources/front.svg"
  elif [ "{{order}}" = "back" ]; then
    layers="{{plot_back_order}}"
    output_file="resources/back.svg"
  else
    echo "Invalid order: '{{order}}'. Must be 'front' or 'back'." >&2
    exit 1
  fi
  kicad-cli pcb export svg --exclude-drawing-sheet --page-size-mode 2 \
    -l "$layers" \
    -o "$output_file" {{pcb_file}}
  # add background rectangle
  svg_width=$(xq '.svg."@width"' "$output_file")
  svg_height=$(xq '.svg."@height"' "$output_file")
  background_rect="<rect x=\"0\" y=\"0\" width=$svg_width height=$svg_height fill=\"#282A36\"/>"
  sed -i "/<desc>Image generated by PCBNEW <\/desc>/a ${background_rect}" "$output_file"
  # change mm to cm
  sed -i -E 's/(width|height)="([0-9]*\.[0-9]*)mm"/\1="\2cm"/g' "$output_file"

pcb:
  #!/usr/bin/env bash
  set -euxo pipefail
  . .env/bin/activate
  python generate.py -out output -f
  just svg {{output}} front
  just svg {{output}} back
  firefox resources/back.svg

# assumes git-lukaj configured, see:
# https://github.com/adamws/lukaj?tab=readme-ov-file#git-integration
diff:
  git diff-svg ./resources/pcb.svg
